# Generated by Django 4.1.2 on 2022-10-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default=5000, max_length=100),
            preserve_default=False,
        ),
    ]
