# Generated by Django 4.1.2 on 2022-10-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('minimum_investment', models.CharField(max_length=50)),
                ('maximum_investment', models.CharField(max_length=50)),
                ('profit', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=20)),
                ('refferal', models.CharField(max_length=20)),
                ('capital_return', models.BooleanField()),
                ('instant_withdrawal', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='investment',
            field=models.ManyToManyField(to='accounts.investment'),
        ),
    ]
