# Generated by Django 4.1.2 on 2022-10-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investment_customuser_investment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='refferal',
            new_name='referral',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='investment',
        ),
        migrations.AddField(
            model_name='customuser',
            name='investment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.investment'),
            preserve_default=False,
        ),
    ]
