# Generated by Django 4.1.2 on 2022-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_refferal_investment_referral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='investment',
        ),
        migrations.AddField(
            model_name='customuser',
            name='current_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='initial_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='investments',
            field=models.ManyToManyField(to='accounts.investment'),
        ),
    ]
