# Generated by Django 4.1.2 on 2022-10-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_investment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.CharField(default='$', max_length=2),
        ),
    ]
