# Generated by Django 4.1.2 on 2022-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roi',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BI-WEEKLY', 'Bi-Weekly')], default='DAILY', max_length=20),
        ),
    ]
