# Generated by Django 4.1.2 on 2022-10-23 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_investments_userinvestment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
