# Generated by Django 4.1.2 on 2022-10-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userinvestment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvestment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
