# Generated by Django 4.1.2 on 2022-10-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_userinvestment_message_userinvestment_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinvestment',
            name='message',
            field=models.CharField(blank=True, default='In Progress', max_length=100, null=True),
        ),
    ]
