# Generated by Django 4.1.2 on 2022-10-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_userinvestment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='amount',
            field=models.IntegerField(default=4000),
            preserve_default=False,
        ),
    ]
