# Generated by Django 4.1.2 on 2022-10-28 00:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_withdrawals_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
