# Generated by Django 4.1.2 on 2022-10-28 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_withdrawals_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawals',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='investments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userinvestment'),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
