# Generated by Django 4.1.2 on 2022-10-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_withdrawals_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawals',
            name='status',
            field=models.CharField(default='In Process', max_length=20),
            preserve_default=False,
        ),
    ]
